name: chameleon_icons_example
description: "Demonstrates how to use the chameleon_icons plugin."
 
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.13.0

 
dependencies:
  flutter:
    sdk: flutter

  chameleon_icons:
    
    path: ../

   
  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^6.0.0


chameleon_icons:
  default_icon:   
    image_path: "assets/icons/chameleon.png"
  alternate_icons:
    dark:
      image_path: "assets/icons/dark_icon.png"
    gold:
      image_path: "assets/icons/gold_icon.png"
  
 
flutter:
 
  uses-material-design: true
  assets:
    - assets/icons/

   